stages:
  - build
  - deploy

build-dev:
  image: node:16
  stage: build
  only:
    - dev
  environment:
    name: dev
  script:
    - echo "$ENV_VARS" | tee .env.local
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

build-stage:
  image: node:16
  stage: build
  only:
    - stage
  environment:
    name: stage
  script:
    - echo "$ENV_VARS" | tee .env.local
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

build-prod:
  image: node:16
  stage: build
  only:
    - prod
  environment:
    name: prod
  script:
    - echo "$ENV_VARS" | tee .env.local
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy-dev:
  image: alpine
  stage: deploy
  only:
    - dev
  environment:
    name: dev
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - echo -e "Host *\n\tPort $SSH_PORT\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 700 -R ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/config
    - rsync -rav --delete dist/ ${SSH_USER_HOST}:${SERVER_PATH}

deploy-stage:
  image: alpine
  stage: deploy
  only:
    - stage
  environment:
    name: stage
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - echo -e "Host *\n\tPort $SSH_PORT\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 700 -R ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/config
    - rsync -rav --delete dist/ ${SSH_USER_HOST}:${SERVER_PATH}

deploy-prod:
  image: alpine
  stage: deploy
  only:
    - prod
  environment:
    name: prod
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - echo -e "Host *\n\tPort $SSH_PORT\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 700 -R ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/config
    - rsync -rav --delete dist/ ${SSH_USER_HOST}:${SERVER_PATH}
